### ISSUE TITLE
pachd will not start on local instance

### ISSUE THREAD

**Issue by kortschak** [pachyderm/pachyderm#1271]
I am trying out pachderm locally, but I am having some problem getting it to consistently start (I have had one successful start).

Now I am seeing things like the following:

```
~ $ minikube start
Starting local Kubernetes cluster...
Kubectl is now configured to use the cluster.
~ $ kubectl get pod
NAME            READY     STATUS             RESTARTS   AGE
etcd-s1cm1      1/1       Running            3          2d
pachd-pxz84     0/1       CrashLoopBackOff   29         2d
rethink-1bgrv   1/1       Running            3          2d
~ $ kubectl logs pachd-pxz84
100: Key not found (/cluster-id) [2]
~ $ dpkg -l pachctl
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                 Version         Architecture    Description
+++-====================-===============-===============-=============================================
ii  pachctl              1.3.3           amd64           ?
```

minikube version is v0.15.0
kubectl version is v1.5.1

I can leave this for quite some time, and the only result is to increase the number of pachd restarts.

**Comment by JoeyZwicker** [comment]
Sorry you ran into this! The key not found error comes from an initialization problem adding the clusterID to etcd if the etcd pod crashes or is rescheduled. We fixed this in pachyderm v1.3.4. Would you mind upgrading to that and try redeploying to see if that fixes the problem?

**Comment by kortschak** [comment]
That does not fix the problem. Do I need to blow the old instances out of the water (they're just tutorial data, so this is not a problem)?

**Comment by JoeyZwicker** [comment]
Just to double check before looking at a other possible causes. Did you
redeploy Pachyderm by bringing down everything back to just the bare
minikube cluster and then `pachctl deploy local` again? So `pachctl
version` returns v1.3.4?

To just make sure there's no state being carried over, you can restart
minikube again too. `minikube delete` then `minikube start`.

**Comment by sjezewski** [comment]
stale
