### ISSUE TITLE
pachctl delete pipeline -> etcdserver: request is too large

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#4118]
While running `pachctl delete pipeline` I got `etcdserver: request is too large`. This happened with `pachctl delete all` too.
Probably related to #3914.
Pachyderm version 1.9.3

**Comment by ppaanngggg** [comment]
The same problem. 
Maybe there are too many commits in releatived pipelines or repos?

**Comment by marcadella** [comment]
I didn't have more than 10 commits (x10 pipelines)

**Comment by pappasilenus** [comment]
@marcadella @ppaanngggg Should have been fixed by https://github.com/pachyderm/pachyderm/pull/4121

Going to close this.  Please reopen if you hit it again.

**Comment by marcadella** [comment]
Still having this issue with 1.9.10 with `pachctl start commit`...

**Comment by echohack** [comment]
Hey @marcadella this is a bit of an old one, but it should be solved with the `--split-transaction` feature we added in 01-2021 for `pachctl delete pipeline`.

If you have any details around what you were running into with `pachctl start commit` could you open a new issue and attach logs of the repro, or add detailed steps to repro? Thank you!
