### ISSUE TITLE
deploy script is broken on 1.9.8

### ISSUE THREAD

**Issue by suneeta-mall** [pachyderm/pachyderm#4285]
trying too run 1.9.8 and I see the yaml spitted out is malformed. I think its printing formatter `                    format: BinarySI` than actual storage size value .. Tried direct deploy which as expected gives same error. 

cmd used ```pachctl deploy XXX ${BUCKET_NAME} ${STORAGE_SIZE} --dynamic-etcd-nodes=1 --output yaml --dry-run```

Snippet below:
```
    volumeClaimTemplates:
      - metadata:
            annotations:
                volume.beta.kubernetes.io/storage-class: etcd-storage-class
            labels:
                app: etcd
                suite: pachyderm
            name: etcd-storage
            namespace: kubeflow
        spec:
            accessModes:
              - ReadWriteOnce
            resources:
                requests:
                    storage:
                        format: BinarySI
---
```

**Comment by msteffen** [comment]
Hi Suneeta, this was due to a change we made in our YAML parser in 1.9.8. Obviously we're focused on getting this fixed as quickly as possible, but in the interim, if it's possible to run your deploy script without `--output yaml` then hopefully you'll be able to avoid this.

**Comment by suneeta-mall** [comment]
@msteffen Yep its not blocking me .. I got my way around .. thanks! 
I was very excited to be trying your TFJob stuff :) Exciting!

**Comment by ronaldosaheki** [comment]
Not only that, but the secret also got weird in yaml deploying to amazon using the same command as @suneeta-mall did:
```
kind: Secret
apiVersion: v1
metadata:
    name: pachyderm-storage-secret
    namespace: pachyderm
    labels:
        app: pachyderm-storage-secret
        suite: pachyderm
data:
    amazon-bucket:
      - 115
      - 116
      - 103
      - 45
      - 115
      - 111
      - 108
      - 111
      - 109
      - 111
      - 110
      - 45
      - 112
      - 97
      - 99
      - 104
      - 121
      - 100
      - 101
      - 114
      - 109
      - 45
      - 112
      - 114
      - 105
      - 99
      - 101
      - 101
      - 118
      - 97
      - 108
      - 117
      - 97
      - 116
      - 105
      - 111
      - 110
    amazon-distribution: []
    amazon-region:
      - 101
      - 117
      - 45
      - 119
      - 101
      - 115
      - 116
      - 45
      - 49
    max-upload-parts:
      - 49
      - 48
      - 48
      - 48
      - 48
    part-size:
      - 53
      - 50
      - 52
      - 50
      - 56
      - 56
      - 48
    retries:
      - 49
      - 48
    reverse:
      - 116
      - 114
      - 117
      - 101
    timeout:
      - 53
      - 109
    upload-acl:
      - 98
      - 117
      - 99
      - 107
      - 101
      - 116
      - 45
      - 111
      - 119
      - 110
      - 101
      - 114
      - 45
      - 102
      - 117
      - 108
      - 108
      - 45
      - 99
      - 111
      - 110
      - 116
      - 114
      - 111
      - 108
---
```

**Comment by JoeyZwicker** [comment]
@msteffen did this get fixed in 1.9.9?

**Comment by theomessin** [comment]
@JoeyZwicker it's not been fixed. I'm using `1.9.9` and I still have this issue.

**Comment by msteffen** [comment]
@theomessin @JoeyZwicker @suneeta-mall @ronaldosaheki Hi all, this should be fixed by https://github.com/pachyderm/pachyderm/pull/4290, which will go out with 1.9.10 by the end of the week.

As before, apologies for throwing a wrench in the works and thanks for being patient with us.
