### ISSUE TITLE
Egress failed to export all data but only a small portion

### ISSUE THREAD

**Issue by panfeng-hover** [pachyderm/pachyderm#5688]
I have met so many times that egress only outputs a small portion of files and gets stuck for no reason. A few files exported at the gs bucket but far from complete.

- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-gke.6000", GitCommit:"b02f5ea6726390a4b19d06fa9022981750af2bbc", GitTreeState:"clean", BuildDate:"2020-11-18T09:16:22Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Pachyderm CLI and pachd server version (use `pachctl version`):
```
$ pachctl version
COMPONENT           VERSION
pachctl             1.11.7
pachd               1.11.7
```

- Cloud provider (e.g. aws, azure, gke): `gke`

The output from `pachctl list job`
```
$ pachctl list job
ID                               PIPELINE STARTED        DURATION RESTART PROGRESS          DL       UL       STATE
9e0fbc3b82d1446599b2bfaf3bdcb3eb tmp      56 minutes ago -        0       36763 + 0 / 36763 141.7MiB 141.7MiB egressing

```
And the duration just keeps increasing, but I didn't see new files in the gs bucket.<br><br><i>(related to <a href='https://pachyderm.zendesk.com/agent/tickets/155'>Zendesk ticket #155</a>)<br>gz#155</i>

**Comment by panfeng-hover** [comment]
Just re-runed the same pipeline got another stuck egressing.

```
$ pachctl list job
ID                               PIPELINE STARTED        DURATION RESTART PROGRESS          DL       UL       STATE
2f2756bfb6604fbb98174c1896210f44 tmp      45 minutes ago -        0       36763 + 0 / 36763 141.7MiB 141.7MiB egressing
```

Is Pachyderm only being able to handle a few hundred files or 36k is too large for Pachyderm?

**Comment by mindthevirt** [comment]
@panfeng-hover this should be working just fine. Could you please upgrade to 1.12.2? There have been multiple performance enhancements implemented since 1.11.7 and also one or two egress bugs have been fixed. Once you upgraded, could you rerun the pipeline and then submit a debug bundle please `pachctl debug dump pachlogs.tar.gz`?

**Comment by panfeng-hover** [comment]
@mindthevirt I just upgraded the pachyderm to 1.12.2, and run a similar pipeline but the egressing problem remains.

```
$ pachctl list job
ID                               PIPELINE  STARTED           DURATION RESTART PROGRESS          DL     UL     STATE
d81497400d8349808a8ceb3975b06cad tmp       About an hour ago -        0       36768 + 0 / 36768 218GiB 218GiB egressing
```

Only 29 / 36768 gets exported.

![image](https://user-images.githubusercontent.com/48805111/107458420-ec1a7780-6b08-11eb-880a-7c2d9b0ce809.png)

**Comment by mindthevirt** [comment]
@panfeng-hover I just went through the logs and it looks like worker pods are not scheduled due to:
`"reason":"0/50 nodes are available: 50 Insufficient memory`
The above log was found in pachlogs/pipelines/tmp/pod/*/storage/logs

`kubectl get pods` and `kubectl get nodes` will likely show them as pending or at least not as running.

**Comment by panfeng-hover** [comment]
I do see the pods are still running and the memory & cpu usage of the Kubernetes instances quickly dropped after the job state changes from running to egressing.

**Comment by mindthevirt** [comment]
@panfeng-hover could you join our Slack channel (https://www.pachyderm.com/slack/)? This will allow us to debug this a bit more real-time + we may just want to jump on a zoom

**Comment by panfeng-hover** [comment]
@mindthevirt Just joined. 

I think the logs of the tmp pipeline looks all right:

`2021-02-10T02:42:40Z INFO pps.API.ListPipeline {"duration":0.237751885,"request":{"allow_incomplete":true},"response":{"pipeline_info":[{"pipeline":{"name":"tmp"},"version":1,"transform":{"image":"us.gcr.io/a8n-playground/auto-matcher:caac066","cmd":["python","/home/data/tmp_export_repo.py","--export_repo","/pfs/manowar","--tmp_repo","/pfs/out"],"err_cmd":["bash"],"image_pull_secrets":["gcr"],"err_stdin":["exit 0"]},"parallelism_spec":{"constant":100},"egress":{"URL":"gs://auto_matcher_pach/manowar/v1.0"},"created_at":{"seconds":1612921230,"nanos":910615620},"state":1,"job_counts":{"0":0,"1":1},"last_job_state":1,"output_branch":"master","resource_requests":{"cpu":0.5,"memory":"512Mi"},"resource_limits":{"cpu":1,"memory":"1024Mi"},"input":{"pfs":{"name":"manowar","repo":"manowar","branch":"master","glob":"/*/*"}},"description":"A pipeline that temporarily export existing repo to gs bucket, and should be deleted after finishing","cache_size":"64M","salt":"7be570863d354524ad489ef3e91b37a1","max_queue_size":1,"datum_timeout":{"seconds":300},"spec_commit":{"repo":{"name":"__spec__"},"id":"2eedf1bda8d34fb4a2170c603d8f043a"},"standby":true,"datum_tries":3},`

The one with `Insufficient memory` is another pipeline, occlusion:

`{"pipeline":{"name":"occlusion"},"version":1,"transform":{"image":"us.gcr.io/a8n-playground/auto-matcher:e2001fe","cmd":["python","/home/data/occlusion_infer.py","--manowar_repo","/pfs/manowar","--occlusion_repo","/pfs/out"],"err_cmd":["bash"],"image_pull_secrets":["gcr"],"err_stdin":["exit 0"]},"parallelism_spec":{"constant":200},"created_at":{"seconds":1612919236,"nanos":73472881},"state":6,"job_counts":{"0":0,"1":1},"last_job_state":1,"output_branch":"master","resource_requests":{"cpu":2,"memory":"2048Mi"},"resource_limits":{"cpu":4,"memory":"4096Mi"},"input":{"pfs":{"name":"manowar","repo":"manowar","branch":"master","glob":"/*/*/*.jpg"}},"description":"A pipeline that generate occlusion masks","cache_size":"64M","salt":"77f532078d2d4ae3a293086e2d8dc774","reason":"0/50 nodes are available: 50 Insufficient memory.","max_queue_size":1,"datum_timeout":{"seconds":300},"spec_commit":{"repo":{"name":"__spec__"},"id":"ba0be138e6b647919f4c0927b5576a6c"},"standby":true,"datum_tries":3}]}}=`

**Comment by pappasilenus** [comment]
Confirmed that manually egressing data in user code works fine, so it's not a rate limiting item.  We should add to backlog and prioritize.

**Comment by pappasilenus** [comment]
Agent comment from David Echo in <a href='https://pachyderm.zendesk.com/agent/tickets/155'>Zendesk ticket #155</a>:<br><br>Marking this as a bug to be solved by eng. Following up with engineering to give an update to the customer when progress is made.

**Comment by pappasilenus** [comment]
Agent comment from David Echo in <a href='https://pachyderm.zendesk.com/agent/tickets/155'>Zendesk ticket #155</a>:<br><br>Ref: https://pachyderm.slack.com/archives/CSELV66P5/p1612480527065700

**Comment by pappasilenus** [comment]
Agent comment from David Echo in <a href='https://pachyderm.zendesk.com/agent/tickets/155'>Zendesk ticket #155</a>:<br><br>I've centralized some of the tracking on this issue:

Github: https://github.com/pachyderm/pachyderm/issues/5688
Zendesk: https://pachyderm.zendesk.com/agent/tickets/155

Refs: 
https://pachyderm.slack.com/archives/CSELV66P5/p1612480527065700
https://pachyderm.slack.com/archives/CSELV66P5/p1613087214109000
https://pachyderm.slack.com/archives/CSELV66P5/p1613506479145600
https://pachyderm-users.slack.com/archives/C3UN0S0Q0/p1612998550145400
https://pachyderm-users.slack.com/archives/C3UN0S0Q0/p1613023152155800
https://pachyderm-users.slack.com/archives/C3UN0S0Q0/p1613083880161400
https://pachyderm-users.slack.com/archives/C3UN0S0Q0/p1613122986167000

**Comment by mindthevirt** [comment]
<div>Agent Dale Georg linked Freshdesk ticket <a href="https://pachyderm-support.freshdesk.com/a/tickets/267">267</a> for this issue.</div>

**Comment by mindthevirt** [comment]
<div>Agent Dale Georg created comment. </div></br><div style="font-family:-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, sans-serif; font-size:14px">
<div dir="ltr">
<div dir="ltr">Hi Panfeng,<br><br>I've been going through open GitHub issues and making sure that we have corresponding tickets in Freshdesk, our new Support management system. I came across this one, which was last updated in February. It doesn't look like it was ever resolved. Can you confirm for me if this is still an issue for you?</div>
<div dir="ltr">​</div>
<div dir="ltr">Thanks,</div>
<div dir="ltr">Dale</div>
<div dir="ltr">
<br><br>
</div>
</div>
<div dir="ltr"><div><br></div></div>
</div>

**Comment by mindthevirt** [comment]
<div>Agent Dale Georg created comment. </div></br><div style="font-family:-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, sans-serif; font-size:14px"><div dir="ltr">Per discussion with Panfeng on June 7th during the bi-weekly Hover status call, he is no longer using egress, but rather is copying the files to the additional S3 bucket(s) within his user code.  Thus, we're going to close this ticket, and if they have issues with egress in the future, they can either open a new ticket or re-open this one.</div></div>
