### ISSUE TITLE
Progress Not Being Shown on pahctl list job Until Job Completes (2.0.0-alpha.18)

### ISSUE THREAD

**Issue by dgeorg42** [pachyderm/pachyderm#6202]
When running `pachctl list job` in 1.13.2 and earlier, the "Progress" column for a running job is periodically updated as the workers commit their output.  So, for example, if there are 2,000 datums to process, it will initially show "0 + 0 / 2000", and then as work progresses it will be updated to show "500 + 0 / 2000", "1000 + 0 / 2000", etc. until the job completes and it shows "2000 + 0 / 2000" (assuming no datums are skipped).

With 2.0, however, for the entire time the job is running the "Progress" column shows "0 + 0 / 0", meaning you have no idea how many datums even need to be processed, let alone what the progress is. As soon as the job completes, "Progress" updates to show "2000 + 0 / 2000".

**Comment by nitinjainsj** [comment]
Retest after global ID changes.

**Comment by brycemcanally** [comment]
This is expected behavior, but we have a straightforward path to making this change.

**Comment by brycemcanally** [comment]
This should be fixed in the most recent alpha.

**Comment by dgeorg42** [comment]
Re-opening this issue as I still see the same behavior in Beta 1.  Also, even if I run `pachctl inspect job` it is showing 0 datums processed while the job is running. I've confirmed by looking at the logs for the pipeline's user container that datums are, in fact, being processed.

**Comment by dgeorg42** [comment]
Never mind, it's working as expected. It just took longer than I'd expected to get to the point where the progress was showing.  And "inspect job" shows the same thing as "list job", which again is expected since we're no longer trying to provide a more granular view there.

**Comment by brycemcanally** [comment]
Yeah, the updating of the job status went through two iterations since this issue was opened. The first would give you the skipped almost immediately, but that did not work well with our parallel job functionality. It now gives you the skipped after the datums that can be processed in parallel are processed. We have a path forward for getting the skipped earlier, but I think this is likely to be the semantics for 2.0. So, the datums that can be processed in parallel will get added as they are processed, then the skipped datums and datums that have to be processed serially (with respect to jobs) will show up.
